### CREATE a new order for alice SELL
POST {{order}}
Content-Type: application/json

{
  "owner": "Alice",
  "timestamp": 123456789,
  "ticker": "LMNO",
  "quantity": 3,
  "side": "SELL",
  "type": "LIMIT",
  "limit": 10
}

### CREATE a new order for bob BUY
POST {{order}}
Content-Type: application/json

{
  "owner": "Bob",
  "timestamp": 123456789,
  "ticker": "LMNO",
  "quantity": 5,
  "side": "BUY",
  "type": "MARKET",
  "limit": 40
}

### GET an order
GET {{order}}/e36d3c83-a63f-47a2-aef2-46403843f8cd



### GET new price for order
GET {{price}}/LMNO

### PATCH filled
PATCH {{order}}/c9153b71-271f-426c-a8bb-49d37658968f
Content-Type: application/json

{
  "filled": 2
}


### GET by username
GET {{order}}/by-user/piclol

### GET by ticker and side
GET {{order}}/open/by-ticker/LNRD/SELL