### CREATE a new order for user test SELL
POST {{order}}
Content-Type: application/json

{
  "owner": "test",
  "timestamp": 457696995,
  "ticker": "LNRD",
  "quantity": 10,
  "side": "SELL",
  "type": "LIMIT",
  "limit": 100,
  "filled": 0
}

### CREATE a new order for user test2 BUY
POST {{order}}
Content-Type: application/json

{
  "owner": "test2",
  "timestamp": 457696995,
  "ticker": "LNRD",
  "quantity": 10,
  "side": "BUY",
  "type": "LIMIT",
  "limit": 100,
  "filled": 0
}

### GET an order
GET {{order}}/54a82a00-951f-4039-84ea-1b6feff253b5

### PATCH filled
PATCH {{order}}/c9153b71-271f-426c-a8bb-49d37658968f
Content-Type: application/json

{
  "filled": 2
}


### GET by username
GET {{order}}/by-user/picsou


### GET by ticker and side
GET {{order}}/open/by-ticker/LNRD/SELL