### Get net-worth of a owner
GET {{wallet}}/pica/net-worth

### Get open wallet of a owner
GET {{wallet}}/pica

### post a list of new positions to wallet
POST {{wallet}}/pica
Content-Type: application/json

[
  {
    "ticker": "CPT",
    "quantity": 100,
    "unitValue": 10
  },
  {
    "ticker": "RAF",
    "quantity": -4,
    "unitValue": 20
  },
  {
    "ticker": "EDC",
    "quantity": 8,
    "unitValue": 30
  }
]
