### CREATE a new order for user test side SELL
POST {{order}}
Content-Type: application/json

{
  "owner": "test",
  "timestamp": 457696995,
  "ticker": "LNRD",
  "quantity": 10,
  "side": "SELL",
  "type": "LIMIT",
  "limit": 100,
  "filled": 0
}

### CREATE a new order for user test2 side BUY
POST {{order}}
Content-Type: application/json

{
  "owner": "test2",
  "timestamp": 457696995,
  "ticker": "LNRD",
  "quantity": 10,
  "side": "BUY",
  "type": "LIMIT",
  "limit": 100,
  "filled": 0
}


###
POST {{execution}}/LNRD/test/test2
Content-Type: application/json

{
  "ticker": "LNRD",
  "seller": "test",
  "buyer": "test2",
  "sell_order_guid": "7ec43267-dccb-4f18-ba67-600edeeab7f0",
  "buy_order_guid": "eb111b7c-4578-4163-93bd-b5939c8dc927",
  "quantity": -1,
  "price": 1
}

### GET by username test
GET {{order}}/by-user/test

### GET by username test2
GET {{order}}/by-user/test2

### GET price by ticker LNRD
GET {{price}}/LNRD