### GET PRICE in db
http://localhost:9004/price/LNRD
### GET PRICE not in db
http://localhost:9004/price/ABCD

### PATCH price in db
PATCH {{price}}/LNRD
Content-Type: application/json

999

### PATCH price not in db
PATCH {{price}}/ABCD
Content-Type: application/json

700

### GET Price updated that was not in db
GET {{price}}/ABCD



