###
GET http://localhost:9001/investor/{{username}}

###
POST http://localhost:9001/investor/{{username}}
Content-Type: application/json

{
  "investor_data": {
    "username": "pica",
    "email": "piceou@canardville.com",
    "firstname": "Scerooge",
    "lastname": "MzcDuck",
    "birthdate": "15/12/1947"
  },
  "password": "get_rich_fast"
}

###
PUT http://localhost:9001/investor/{{username}}
Content-Type: application/json

{
    "username": "pica",
    "email":"piceou@canardvidzadddadaadalle.com",
    "firstname": "dadda",
    "lastname": "MzcDuckz",
    "birthdate": "30/12/2022"
}

###
DELETE http://localhost:9001/investor/{{username}}
