###
GET {{investor}}/pica

###
POST {{investor}}/pica
Content-Type: application/json

{
  "investor_data": {
    "username": "pica",
    "email": "piceou@canardville.com",
    "firstname": "Scerooge",
    "lastname": "MzcDuck",
    "birthdate": "15/12/1947"
  },
  "password": "get_rich_fast"
}

###
PUT {{investor}}/pica
Content-Type: application/json

{
  "username": "pica",
  "email": "piceou@a.com",
  "firstname": "abc",
  "lastname": "MzcDuckz",
  "birthdate": "30/12/2022"
}

###
DELETE {{investor}}/pica
