
### POST /investor/{username} - Create investor 1 (success)
POST {{gateway}}/investor/pica
Content-Type: application/json

{
  "investor_data": {
    "username": "pica",
    "email": "piceou@canardville.com",
    "firstname": "Scerooge",
    "lastname": "MzcDuck",
    "birthdate": "15/12/1947"
  },
  "password": "get_rich_fast"
}


### POST /investor/{username} - Create investor 2 (success)
POST {{gateway}}/investor/investor2
Content-Type: application/json

{
  "investor_data": {
    "username": "investor2",
    "email": "abc@gmail.com",
    "firstname": "test",
    "lastname":"test",
    "birthdate": "20/01/2020"
  },
  "password": "password"
}

### GET /investor/{username} - Get investor by username
GET {{gateway}}/investor/pica

### GET /investor/{username} - Get investor who does not exist (error 404)
GET {{gateway}}/investor/random

### PUT /investor/{username} - Update investor
PUT {{gateway}}/investor/pica
Content-Type: application/json

{
  "username": "pica",
  "email": "picesou@canardlaque.can",
  "firstname": "Pic",
  "lastname": "Sou",
  "birthdate": "30/12/2022"
}

### DELETE /investor/{username} - Delete investor (success)
DELETE {{gateway}}/investor/investor2

### POST /authentication/connect - Connect investor (success)
POST {{gateway}}/authentication/connect
Content-Type: application/json

{
  "username": "pica",
  "password": "get_rich_fast"
}

> {% client.global.set("token", response.body) %}

### PUT /authentication/{username} - Update investor credentials (success)
PUT {{gateway}}/authentication/pica
Content-Type: application/json

{
  "username": "pica",
  "password": "get_rich_faster"
}

### POST /order - Create order (success)
POST {{gateway}}/order
Content-Type: application/json

{
  "owner": "test2",
  "timestamp": 457696995,
  "ticker": "NVDA",
  "quantity": 10,
  "side": "BUY",
  "type": "LIMIT",
  "limit": 100,
  "filled": 0
}

### POST /order - Create orders for pica
POST {{gateway}}/order
Content-Type: application/json

{
  "owner": "pica",
  "timestamp": 457696995,
  "ticker": "AMDT",
  "quantity": 50,
  "side": "SELL",
  "type": "MARKET",
  "limit": 100,
  "filled": 0
}

### POST /order - Create orders for pica
POST {{gateway}}/order
Content-Type: application/json

{
  "owner": "pica",
  "timestamp": 457696995,
  "ticker": "MORT",
  "quantity": 50,
  "side": "SELL",
  "type": "MARKET",
  "limit": 100,
  "filled": 0
}

### GET /order/by-user/{username} - Get orders by username
GET {{gateway}}/order/by-user/pica
Authorization: {{token}}

### GET /order/by-user/{username} - Get orders for an other user (Unauthorized)
GET {{gateway}}/order/by-user/test2
Authorization: {{token}}



