### GET PRICE in db (success, returns price in db)
http://localhost:9004/price/LNRD

### GET PRICE not in db (success returns price 1)
http://localhost:9004/price/ABCD

### PATCH price in db (success)
PATCH {{price}}/LNRD
Content-Type: application/json

999

### GET PRICE in db (to show updated price 999)
http://localhost:9004/price/LNRD

### PATCH price not in db (success)
PATCH {{price}}/ABCD
Content-Type: application/json

700

### GET PRICE new in db
GET http://localhost:9004/price/ABCD

### GET Price updated that was not in db (now in db)
GET {{price}}/ABCD



