### Get user named Pica
GET {{investor}}/pic

### Create user named Pica and its credentials
POST {{investor}}/pic
Content-Type: application/json

{
  "investor_data": {
    "username": "pic",
    "email": "piceou@canardville.com",
    "firstname": "Scerooge",
    "lastname": "MzcDuck",
    "birthdate": "15/12/1947"
  },
  "password": "get_rich_fast"
}

### Connect user named Pica
POST {{authentication}}/connect
Content-Type: application/json

{
  "username": "pica",
  "password": "get_rich_fast"
}

### Update user named Pica
PUT {{investor}}/pica
Content-Type: application/json

{
  "username": "pica",
  "email": "piceou@a.com",
  "firstname": "abc",
  "lastname": "MzcDuckz",
  "birthdate": "30/12/2022"
}

### Delete user named Pica and its credentials
DELETE {{investor}}/pica


### Connect user named Pica
POST {{authentication}}/connect
Content-Type: application/json

{
  "username": "pica",
  "password": "get_rich_fast"
}
