### GET PRICE in db
http://localhost:9002/price/LNRD
### GET PRICE not in db
http://localhost:9002/price/ABCD

### PATCH price in db
PATCH http://localhost:9002/price/LNRD
Content-Type: application/json

999

### PATCH price not in db
PATCH http://localhost:9002/price/ABCD
Content-Type: application/json

700

### GET Price updated that was not in db
GET http://localhost:9002/price/ABCD



