### Create safeCredentials
POST {{authentication}}/Cat4Life
Content-Type: application/json

{
  "username": "Cat4Life",
  "password": "NotSaying!1234"
}

### Update safeCredentials
PUT {{authentication}}/Cat4Life
Content-Type: application/json

{
  "username": "Cat4Life",
  "password": "pas"
}

### Delete safeCredentials
DELETE {{authentication}}/Cat4Life

### Connect user
POST {{authentication}}/connect
Content-Type: application/json

{
  "username": "Cat4Life",
  "password": "pas"
}

### Verify token
POST http://localhost:9002/authentication/verify
Content-Type: application/json

